AWSTemplateFormatVersion: '2010-09-09'
Description: 'Auxiliary sidecar resources for ppc-ecommerce-product-service'

Resources:
  ProductS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'ppc-ecommerce-product-assets-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
