spring.application.name=ppc-ecommerce-product-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Servlet Context Path (Matches Repository Name)
server.servlet.context-path=/ppc-ecommerce-product-service

# Server Port
server.port=${PORT:8081}

# Actuator Health Check for ALB
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
